site_name: Virtual Anatomy docs 
include_sidebar: false
site_description: 'Documentation for VirtualAnatomy'
site_author: 'JRCZ'
site_url: https://jrcz-data-science-lab.github.io/VirtualAnatomy-Documentation/
docs_dir: docs
repo_name: 'Virtual-Anatomy-Docs'
repo_url: 'https://github.com/jrcz-data-science-lab/3D-Anatomy-Documentation'
markdown_extensions:
  - attr_list
  - md_in_html


copyright: <h3><i>© 2024 Joint Research Center Zeeland. All Rights Reserved.

theme:
  name: material
  palette:
  - scheme: slate
    primary: red
    accent: red
    toggle: 
      icon: material/weather-sunny 
      name: Switch to dark mode
  - scheme: indigo
    primary: indigo
    accent: indigo
    toggle: 
      icon: material/weather-night
      name: Switch to light mode
 