site_name: Virtual Anatomy docs 
include_sidebar: false
site_description: 'Documentation for VirtualAnatomy'
site_author: 'JRCZ'
site_url: https://jrcz-data-science-lab.github.io/VirtualAnatomy-Documentation/
docs_dir: docs/
repo_name: 'Virtual-Anatomy-Docs'
repo_url: 'https://github.com/jrcz-data-science-lab/3D-Anatomy-Documentation'
markdown_extensions:
  - attr_list
  - md_in_html
nav:
  - Home: index.md
  - About Project: about-project.md
  - Virtual Anatomy:
      - Introduction: VirtualAnatomy/Introduction.md
      - Linux Set-Up: VirtualAnatomy/Linux-set-up.md
      - Explorer Level:
          - Animations:
            - General: VirtualAnatomy/ExplorerLevel/Animations/Animations.md
            - BaseAnimationClass: VirtualAnatomy/ExplorerLevel/Animations/BaseAnimationClass.md
          - Anatomy Helpers: VirtualAnatomy/ExplorerLevel/AnatomyHelpers.md
          - Character: VirtualAnatomy/ExplorerLevel/Character.md
          - First Steps: VirtualAnatomy/ExplorerLevel/FirstSteps.md
          - Mesh Selector: VirtualAnatomy/ExplorerLevel/MeshSelector.md
          - Ray Casting: VirtualAnatomy/ExplorerLevel/RayCasting.md
          - Simulation: 
            - General overview: VirtualAnatomy/ExplorerLevel/Simulation/GeneralOverview.md  
            - Blood flow simulation: VirtualAnatomy/ExplorerLevel/Simulation/BloodFlowSimulaiton.md
          - UI:
            - GeneralAproach: VirtualAnatomy/ExplorerLevel/UI/HowIsUIDone.md
            - UI Classes:
              - SimulationButton: VirtualAnatomy/ExplorerLevel/UI/SimulationButton.md
              - Clicked on info: VirtualAnatomy/ExplorerLevel/UI/ClickedOnInfo.md
              - Simulation Island: VirtualAnatomy/ExplorerLevel/UI/SimulationIsland.md

      - Main Menu Level:
          - Landing Page: VirtualAnatomy/MainMenuLevel/LandingPage.md  
theme: 
  name: material
  palette:
  - scheme: red
    primary: red
    accent: red
    toggle: 
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - scheme: orange
    primary: deep-orange
    accent: orange
    toggle: 
      icon: material/toggle-switch
      name: Switch to light mode
  - scheme: yellow
    primary: yellow
    accent: yellow
    toggle: 
      icon: material/weather-sunny
      name: Switch to dark mode
  - scheme: green 
    primary: green
    accent: green
    toggle: 
      icon: material/weather-night
      name: Switch to light mode
  - scheme: light-blue 
    primary: light-blue
    accent: light-blue
    toggle: 
      icon: material/eye-outline
      name: Switch to light mode
  - scheme: indigo 
    primary: indigo
    accent: indigo
    toggle: 
      icon: material/eye
      name: Switch to light mode
  - scheme: purple 
    primary: purple
    accent: purple
    toggle: 
      icon: material/lightbulb-outline
      name: Switch to light mode
