site_name: Virtual Anatomy documentation
include_sidebar: false
site_description: 'Documentation for the Virtual Anatomy project'
site_author: 'JRCZ'
site_url: https://jrcz-data-science-lab.github.io/VirtualAnatomy-Documentation/
docs_dir: docs
repo_name: 'Virtual-Anatomy-UE'
repo_url: 'https://github.com/jrcz-data-science-lab/Virtual-Anatomy-UE'
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - mkdocs-nav-weight

copyright: <h3><i>© 2025 Joint Research Center Zeeland. All Rights Reserved.

theme:
  name: material
  palette:
  - scheme: slate
    primary: red
    accent: red
    toggle: 
      icon: material/weather-sunny 
      name: Switch to dark mode
  - scheme: indigo
    primary: indigo
    accent: indigo
    toggle: 
      icon: material/weather-night
      name: Switch to light mode
 
